### ISSUE TITLE
Red text, error\exception

### ISSUE THREAD

**Issue by amaroc** [lavigor/vk#1]
3.3.0-a1-dev - версия phpBB.
OS: freebsd 10.3

Загрузил приложение, авторизовал как положено в админ панели:
/forum/ext/lavigor/vk # ls
LICENSE.txt     auth            config          migrations
README.md       composer.json   event

Папка с форумом абсолютный путь:
/usr/local/www/apache24/data/forum/

Выдало ошибку красным фоном:

```
CONTAINER_EXCEPTION

EXCEPTION: The file "/usr/local/www/apache24/data/forum/ext/lavigor/vk/config/services.yml" does not contain valid YAML.
#0 /usr/local/www/apache24/data/forum/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(69): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/usr/local/www/...')
#1 /usr/local/www/apache24/data/forum/phpbb/extension/di/extension_base.php(99): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('services.yml')
#2 /usr/local/www/apache24/data/forum/phpbb/extension/di/extension_base.php(63): phpbb\extension\di\extension_base->load_services(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#3 /usr/local/www/apache24/data/forum/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(55): phpbb\extension\di\extension_base->load(Array, Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#4 /usr/local/www/apache24/data/forum/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /usr/local/www/apache24/data/forum/vendor/symfony/dependency-injection/Compiler/Compiler.php(120): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 /usr/local/www/apache24/data/forum/vendor/symfony/dependency-injection/ContainerBuilder.php(565): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 /usr/local/www/apache24/data/forum/phpbb/di/container_builder.php(186): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#8 /usr/local/www/apache24/data/forum/common.php(115): phpbb\di\container_builder->get_container()
#9 /usr/local/www/apache24/data/forum/adm/index.php(23): require('/usr/local/www/...')
#10 {main}
```

Видимо по этому в окне авторизацей не появляется поле VK Auth для ввода ключей. Все осталось как было. Что делать?

**Comment by amaroc** [comment]
С приложением конкурента (aaaler) та же самая история =) Я погуглил пишут что то про версии php и какого то yaml https://github.com/o0johntam0o/phpBB-Extension-Codebox-Plus/issues/14 

Моя версия PHP 5.6.24 (cli) (built: Jul 28 2016 01:52:24)

**Comment by lavigor** [comment]
Добавил кавычки в этот файл.
Проблема должна исчезнуть.

Однако полная совместимость всё равно не гарантируется, как и стабильная работа самой альфа версии новой ветки движка.

**Comment by amaroc** [comment]
Супер что так оперативно! Активировал расширение - красное предупреждение
это пропало :)

Но слетели все языки в админ панели - /forum/adm/ - вместо локализации
показывает  ACP_CAT_GENERAL
ACP_CAT_FORUMS
ACP_CAT_POSTING
ACP_CAT_USERGROUP
ACP_CAT_PERMISSIONS
ACP_CAT_CUSTOMISE
ACP_CAT_MAINTENANCE
ACP_CAT_SYSTEM и так далее.

А так аутентификация теперь проходит! Супер
